apiVersion: apps/v1
kind: Deployment
metadata:
  name: tour
  labels:
    app: tour
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tour
  template:
    metadata:
      labels:
        app: tour
    spec:
      containers:
        - name: cont1
          image: prat1402/tour:latest
      
                          
